In [4]:
import numpy as np

arr = np.array([[1,2,3],
              [4,5,6]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

# Array Creation


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [13]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
d = np.ones((3,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange?


In [16]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [17]:
np.linspace(0,30,5) # seven values in the range of 0,30

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [18]:
arr = arr.reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
new_arr = arr.flatten()
new_arr

array([1, 2, 3, 4, 5, 6])

In [20]:
A = np.array([[1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[1,5,8,0]])

In [21]:
A[1:,:3]

array([[ 4. , -0.5,  6. ],
       [ 2.6,  0. ,  7. ],
       [ 1. ,  5. ,  8. ]])

In [22]:
#stepwise [starting index:ending index+1:stepsize, starting index:ending index+1:stepsize]
A[0:, :3:2]

array([[1. , 0. ],
       [4. , 6. ],
       [2.6, 7. ],
       [1. , 8. ]])

In [23]:
temp = A[:2,::2]

In [24]:
temp = A[[0,1,2,3],[3,2,1,0]]

In [27]:
cond = A>0
temp = A[cond]
temp

array([1. , 2. , 4. , 4. , 6. , 2.6, 7. , 8. , 1. , 5. , 8. ])

 # Basic Operations 

In [28]:
a = np.array([1,2,3,4,5])

In [29]:
a+1

array([2, 3, 4, 5, 6])

In [30]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [31]:
a.T #transpose

array([1, 2, 3, 4, 5])

In [32]:
arr.max()

6

In [33]:
arr.max(axis=1) #rowise maximum

array([2, 4, 6])

In [34]:
arr.max(axis=0)

array([5, 6])

In [35]:
arr.min()

1

In [36]:
arr.sum()

21

In [37]:
sum(arr)

array([ 9, 12])

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6])

a+b

array([5, 7, 9])

In [39]:
a*b

array([ 4, 10, 18])

In [40]:
a.dot(b)

32

In [41]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [42]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [43]:
np.sort(a)

array([1, 2, 3])

In [44]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=[15,61]

In [45]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [44]:
np.column_stack((a,c))

array([[ 1,  2, 15],
       [ 3,  4, 61]])

In [46]:
np.concatenate((a,b),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [50]:
np.hsplit(a,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [51]:
np.vsplit(a,2)

[array([[1, 2]]), array([[3, 4]])]

In [52]:
np.mean(a)

2.5

In [47]:
np.median(a)

2.5

In [48]:
np.average(a)

2.5

In [49]:
a=np.arange(10)+5

In [52]:
a

array([ 9,  6, 10,  5, 12,  7,  8, 11, 14, 13])

In [57]:
np.random.seed(1)

In [58]:
np.random.shuffle(a)

In [59]:
a

array([ 6, 14, 11, 13,  7, 10, 12,  9,  5,  8])

In [60]:
a=np.random.randn(2,3)

In [61]:
a

array([[ 1.5827523 , -1.04514683,  0.25759352],
       [-1.9593946 , -1.50780766, -0.31529207]])

In [62]:
a=np.random.randint(5,10,3)

In [63]:
a

array([7, 9, 6])

In [64]:
element = np.random.choice([4,5,2,3,7])

In [65]:
element

5

In [72]:
a = np.random.random(6)
a

array([0.19810149, 0.80074457, 0.96826158, 0.31342418, 0.69232262,
       0.87638915])