# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [6]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [12]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [15]:
x.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [17]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [19]:
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [30]:
y=np.arange(10,50)
print(y)
z= np.linspace(10,50,5)
z

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([10., 20., 30., 40., 50.])

#### 8.  Reverse a vector (first element becomes last)

In [26]:
arr=[1,2,3,4,5]
rev=arr[::-1]
rev

[5, 4, 3, 2, 1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [36]:
b=[1,2,0,0,4,0]
for i in range(0,6):
    if(b[i]>0):
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [37]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [47]:

d=np.random.random((3,3,3))
d

array([[[0.78161289, 0.56475814, 0.73815623],
        [0.6140998 , 0.25166012, 0.45656269],
        [0.81090495, 0.22543362, 0.98776737]],

       [[0.83565202, 0.07080756, 0.06513641],
        [0.29325395, 0.21692645, 0.55820838],
        [0.01217636, 0.31452152, 0.31749383]],

       [[0.24360226, 0.97561334, 0.04806589],
        [0.88474695, 0.37124274, 0.66860176],
        [0.29886766, 0.48437678, 0.12659901]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [52]:
e=np.random.random((10,10))
e
np.min(e)
np.max(e)

0.9913636919934721

#### 14. Create a random vector of size 30 and find the mean value

In [55]:
f=np.random.random(30)
np.mean(f)

0.4962670305996549

### 15. Create a 2d array with 1 on the border and 0 inside

In [60]:
g=np.zeros((5,5))

for i in range(0,5):
    g[0][i]=1
    g[4][i]=1
for i in range(0,5):
    g[i][0]=1
    g[i][4]=1

g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [63]:
h=np.ones((3,3))
h=np.pad(h,pad_width=1,mode='constant',constant_values=0)
h

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
import numpy as np
np.nan

In [7]:
# np.nan == np.nan
np.isnan(np.nan) 
# object to object comparison so different 

True

In [69]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [70]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [71]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [72]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
